# Generated by Django 3.1.6 on 2021-02-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=15)),
                ('section_a', models.CharField(default='A', max_length=2)),
                ('section_b', models.CharField(blank=True, max_length=2, null=True)),
                ('section_c', models.CharField(blank=True, max_length=2, null=True)),
                ('section_d', models.CharField(blank=True, max_length=2, null=True)),
                ('section_e', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ST', max_length=20)),
                ('password', models.CharField(max_length=500)),
                ('admission_no', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('section', models.CharField(max_length=2)),
                ('image', models.ImageField(upload_to='student')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.class')),
            ],
        ),
    ]
