# Generated by Django 3.1.6 on 2021-02-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='admission_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='students',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
