# Generated by Django 3.1.6 on 2021-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20210218_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
