# Generated by Django 3.1.6 on 2021-02-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_students_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_no',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
