# Generated by Django 3.1.6 on 2021-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='TE', max_length=20),
        ),
    ]
