# Generated by Django 3.1.6 on 2021-02-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_auto_20210222_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(default='All', max_length=10)),
                ('type', models.CharField(default='Holiday', max_length=10)),
                ('date', models.DateField()),
                ('notice', models.TextField()),
                ('add_notice_date', models.DateTimeField(auto_now_add=True, verbose_name='add_notice_data')),
            ],
        ),
    ]
