# Generated by Django 3.1.6 on 2021-02-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_notice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notices',
        ),
    ]
