# Generated by Django 3.1.6 on 2021-02-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_remove_notices_add_notice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='A', max_length=2)),
                ('subject_1', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_2', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_3', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_4', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_5', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_6', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_7', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_8', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_9', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_10', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_11', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_12', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_13', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_14', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_15', models.CharField(blank=True, max_length=30, null=True)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.class')),
            ],
        ),
    ]
