# Generated by Django 3.1.6 on 2021-02-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_class_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=20)),
                ('section', models.CharField(blank=True, max_length=2, null=True)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.teacher')),
            ],
        ),
    ]
