# Generated by Django 3.1.6 on 2021-03-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
