# Generated by Django 3.1.6 on 2021-03-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20210301_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.students'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.teacher'),
        ),
    ]
