# Generated by Django 3.1.6 on 2021-03-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_auto_20210302_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='last_login',
        ),
    ]
