# Generated by Django 3.1.6 on 2021-03-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_remove_teacher_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='last_login',
        ),
    ]
