# Generated by Django 3.1.6 on 2021-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_remove_students_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('dob', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('role', models.CharField(default='', max_length=20)),
                ('basic_salary', models.CharField(default='', max_length=30)),
                ('aadhar_number', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
            ],
        ),
    ]
